### PR TITLE
Put { on a new line

### PR DESCRIPTION
**Pull request by BarbzYHOOL**

### CODE REVIEW

**Comment by jonnypolite** [comment]
I can't really find any style guides that recommend this. Are you saying the output would be like this?

```
.example
{
    display: flex;
    border: 1px dashed red;
}
```

Or am I misunderstanding?

**Comment by jonnypolite** [comment]
Here's one example, for reference: https://google.github.io/styleguide/htmlcssguide.html#Declaration_Block_Separation

**Comment by BarbzYHOOL** [comment]
Yes, exactly.

Well yes it's a well known way of doing it but maybe a bit less popular than the other way and even if it weren't recommended, don't you think it look cleaner ? I prefer this one and there are prettifier that give the option. I made the PR mostly for people interested who stumble upon the repo :p


Lol at the link "not recommended" reason "unecessary linebreak". Ridiculous, then this would be fine too

```
#video {
  margin-top: 1em;}
```

0 argument, stupid google

**Comment by jonnypolite** [comment]
Yeah I'm with Google, (and all the other CSS I've ever encountered) on this one. I don't think it looks cleaner. To me the extra line break just takes up space. If the point is to differentiate the name of the selector from the properties it's still unnecessary as this is already achieved by the indents.

I welcome you to fork it though, and put in as many line breaks as your heart desires.

**Comment by BarbzYHOOL** [comment]
https://en.wikipedia.org/wiki/Indentation_style#Allman_style


> I welcome you to fork it though, and put in as many line breaks as your heart desires.

that's what I did, didn't expect an answer here


If you want I can open a PR for this perfect result though:

```
#video {
  margin-top: 1em;}
```

(joking)

**Pull request closed without merging**
